### PR TITLE
new begin() with mostly free pin selection

### PR DESCRIPTION
**Pull request by Adminius**
User can call new begin function like this:
```strip.begin(&sercom4, SERCOM4, SERCOM4_DMAC_ID_TX, 22, 23, 24, SPI_PAD_0_SCK_3, SERCOM_RX_PAD_2, PIO_SERCOM_ALT);```

### CODE REVIEW

**Comment by Adminius** [comment]
#1

**Comment by Adminius** [comment]
i'm not sure about ```boolen```. may be ```bool``` is better

**Comment by Adminius** [comment]
@PaintYourDragon thx!
when is the next release of this lib planned?

**Comment by PaintYourDragon** [comment]
Taa-daah.

**Pull request merged**
